Fix openx function to use command find
The openx function was broken because we aliased 'find' to 'fd',
but fd has different syntax than find. Using 'command find' bypasses
the alias and uses the actual find binary with correct syntax.

Fixes error:
  error: unexpected argument '-m' found